
name: CD - Deploy to VM via Docker Compose

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set IMAGE tag
        id: prep
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/spring-boot-ci-cd-demo:${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Connect & Deploy (SSH)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            export IMAGE=${{ steps.prep.outputs.IMAGE }}
            mkdir -p ~/apps/spring-boot-ci-cd-demo
            cd ~/apps/spring-boot-ci-cd-demo
            echo "version: '3'" > docker-compose.yml
            echo "services:" >> docker-compose.yml
            echo "  app:" >> docker-compose.yml
            echo "    image: $IMAGE" >> docker-compose.yml
            echo "    ports:" >> docker-compose.yml
            echo "      - '8080:8080'" >> docker-compose.yml
            echo "    environment:" >> docker-compose.yml
            echo "      - SPRING_PROFILES_ACTIVE=prod" >> docker-compose.yml
            docker pull $IMAGE
            docker compose up -d
