
name: CD - Deploy to VM via Docker Compose

on:
  push:
    tags:
      - 'v*.*.*'   # ex: v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare IMAGE tag
        id: prep
        run: |
          echo "IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-cd-demo:${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Connect & Deploy (SSH)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            export IMAGE=${{ steps.prep.outputs.IMAGE }}
            mkdir -p ~/apps/spring-boot-ci-cd-demo
            cd ~/apps/spring-boot-ci-cd-demo

            cat > docker-compose.yml <<'YAML'
            version: '3.8'
            services:
              app:
                image: ${IMAGE}
                container_name: spring-boot-ci-cd-demo
                ports:
                  - "8080:8080"
                environment:
                  - SPRING_PROFILES_ACTIVE=prod
                restart: unless-stopped
            YAML

            docker pull $IMAGE
            docker compose up -d
            docker compose ps
